[package]
authors = ["Baptiste Gelez <baptiste@gelez.xyz>"]
description = "Rocket fairing for easy internationalization with gettext"
license = "GPL-3.0"
name = "rocket_i18n"
readme = "README.md"
repository = "https://github.com/BaptisteGelez/rocket_i18n"
keywords = ["i18n", "rocket", "gettext", "internationalization", "localization"]
categories = ["internationalization", "localization", "web-programming"]
version = "0.2.0"

[dependencies]
serde_json = "1.0"
tera = "0.11"
gettext = { git = "https://github.com/justinas/gettext", rev = "e9213976f2e3d418ad367e1bf19bd98f47a42440" }
rocket = "0.4.0-rc.1"

[features]
build = []
